export const transactions = [
    {
        Symbol: 'ALV-GY',
        Name: 'Allianz SE - Registered Shares',
        Type: 'Buy',
        Date: '2020-01-06',
        Shares: 170,
        Price: 167,
        cashValue: '',
        Commission: 0,
        Notes: '',
    },
    {
        Symbol: 'AXA-GY',
        Name: 'AXA SA',
        Type: 'Buy',
        Date: '2020-08-31',
        Shares: 1150,
        Price: 17.14,
        cashValue: '',
        Commission: 0,
        Notes: '',
    },
    {
        Symbol: 'BAS-GY',
        Name: 'Basf SE',
        Type: 'Buy',
        Date: '',
        Shares: 1090,
        Price: 62.48,
        cashValue: '',
        Commission: 0,
        Notes: '',
    },
    {
        Symbol: 'BAYN-GY',
        Name: 'Bayer AG - Registered Shares',
        Type: 'Buy',
        Date: '',
        Shares: 400,
        Price: 57.41,
        cashValue: '',
        Commission: 0,
        Notes: '',
    },
    {
        Symbol: 'BEI-GY',
        Name: 'Beiersdorf AG',
        Type: 'Buy',
        Date: '',
        Shares: 570,
        Price: 86,
        cashValue: '',
        Commission: 0,
        Notes: '',
    },
    {
        Symbol: 'DAI-GY',
        Name: 'Daimler AG',
        Type: 'Buy',
        Date: '',
        Shares: 1200,
        Price: 39.66,
        cashValue: '',
        Commission: 0,
        Notes: '',
    },
    {
        Symbol: 'ECV-GY',
        Name: 'Encavis AG',
        Type: 'Buy',
        Date: '',
        Shares: 12,
        Price: 0,
        cashValue: '',
        Commission: 0,
        Notes: '',
    },
    {
        Symbol: 'ECV-GY',
        Name: 'Encavis AG',
        Type: 'Buy',
        Date: '',
        Shares: 1100,
        Price: 18.22,
        cashValue: '',
        Commission: 0,
        Notes: '',
    },
    {
        Symbol: 'FRE-GY',
        Name: 'Fresenius SE & Co. KGaA',
        Type: 'Buy',
        Date: '',
        Shares: 1200,
        Price: 43.67,
        cashValue: '',
        Commission: 0,
        Notes: '',
    },
    {
        Symbol: 'HOT-GY',
        Name: 'Hochtief AG',
        Type: 'Buy',
        Date: '',
        Shares: 500,
        Price: 98.89,
        cashValue: '',
        Commission: 0,
        Notes: '',
    },
    {
        Symbol: 'LHA-GY',
        Name: 'Deutsche Lufthansa AG',
        Type: 'Buy',
        Date: '',
        Shares: 4500,
        Price: 15.3,
        cashValue: '',
        Commission: 0,
        Notes: '',
    },
    {
        Symbol: 'SAP-GY',
        Name: 'Sap SE',
        Type: 'Buy',
        Date: '',
        Shares: 500,
        Price: 94.05,
        cashValue: '',
        Commission: 0,
        Notes: '',
    },
    {
        Symbol: 'TLG-GY',
        Name: 'TLG Immobilien AG - Bearer Shares',
        Type: 'Buy',
        Date: '',
        Shares: 1850,
        Price: 23.59,
        cashValue: '',
        Commission: 0,
        Notes: '',
    },
    {
        Symbol: 'TUI1-GY',
        Name: 'Tui AG - Registered Shares',
        Type: 'Buy',
        Date: '',
        Shares: 5000,
        Price: 5.17,
        cashValue: '',
        Commission: 0,
        Notes: '',
    },
    {
        Symbol: 'WDI-GY',
        Name: 'Wirecard AG',
        Type: 'Buy',
        Date: '',
        Shares: 300,
        Price: 94.36,
        cashValue: '',
        Commission: 0,
        Notes: '',
    },
]

export const symbols = [
    'ALV-GY', 'AXA-GY', 'BAS-GY', 'BAYN-GY', 'BEI-GY', 'DAI-GY', 'ECV-GY', 'ECV-GY', 'FRE-GY', 'HOT-GY', 'LHA-GY', 'SAP-GY', 'TLG-GY', 'TUI1-GY', 'WDI-GY'
]